package cloudNettyServer.enums;

public enum ActionStage {
    AUTHORIZED,
    UNAUTHORIZED,

    GETTING_COMMAND,
    GETTING_FILE_LENGTH,
    GETTING_FILE_NAME_LENGTH,
    GETTING_FILE_NAME,
    GETTING_FILE_CONTENT,
    SENDING_FILE_CONTENT,
    DELETE_FILES,
    SENDING_FILE_NAME_LIST,
}
