package cloudNettyServer.enums;

public enum ActionStage {
    AUTHORIZED,
    UNAUTHORIZED,
    GETTING_LOGIN_LENGTH,
    GETTING_LOGIN,
    GETTING_PASSWORD_LENGTH,
    GETTING_PASSWORD,
    SIGN_IN,

    GETTING_COMMAND,
    GETTING_FILE_LENGTH,
    GETTING_FILE_NAME_LENGTH,
    GETTING_FILE_NAME,
    GETTING_FILE_CONTENT,
    SENDING_FILE_CONTENT
}
